- docusaurus.config.js
- package.json
- yarn.lock
> Docusaurus AI

- src/css/custom.css
> Custom colors for biel AI button

- docs/documentation/features/delegated-access.md
- docs/sdks/migration.mdx
original: https://docs.google.com/document/d/1ue4RvT1mn-zbGeW7KmAlY078_Bg_n1FYEwZQZSpmDrg/edit?tab=t.0
> add migration path document

- docs/documentation/concepts/Wallets.md
- docs/documentation/ecosystem-integrations/index.md
- docs/documentation/ecosystem-integrations/others.md
- docs/documentation/getting-started/resource-limits.md
- docs/sdks/advanced/_category_.json
- docs/sdks/flutter.mdx
- docs/sdks/web3-libraries/_category_.json
- Added new address format table to Wallets page 
- Link to ^ from ecosystem integrations 
- Flutter page in SDK ref
- Clarification on expiring API key resource limits 
- Minor typo
> Clarifying asset support

- docs/sdks/javascript-browser.mdx
- docs/sdks/javascript-server.mdx
> update spelling of JavaScript

- docs/documentation/features/otp-auth.md
> User identifier info added for rate-limiting SMS users

- docs/documentation/concepts/policy-management/Policy-examples.md
- docs/documentation/concepts/policy-management/Policy-language.md
$title
corresponds to https://github.com/tkhq/mono/pull/3527 (late followup :))
> add wallet account policy to docs

- docs/documentation/FAQ.md
- docs/documentation/security/our-approach.md
- docs/documentation/security/whitepaper.md
Adds references to the Turnkey whitepaper!
> Add whitepaper to docs

- docs/sdks/introduction.mdx
Removing unused URLs from table config
> docs: remove URLs from config

- docs/welcome.mdx
They're broken so I've updated them.
> Update support and X links

- docs/documentation/authentication/email.mdx
- docs/documentation/authentication/sms.mdx
> add rate limit details

- docs/documentation/getting-started/quickstart/embedded-wallet-quickstart.mdx
I was playing with this quickstart, it didn't work unless adding these changes - would love to get some eyes on it:
- added src/app/layout.tsx in complete code
- needed to import useRouter from next/navigation in src/app/page.tsx
- useState is a client-side hook, added the "use client"; directive in src/app/dashboard/page.tsx
- wrapped getCurrentUser within an async function, otherwise organizationId would not be available within getSignWith()
> embedded-wallet-quickstart updates

- docs.json
- wallets/claim-links.mdx
- wallets/export-wallets.mdx
- wallets/import-wallets.mdx
- Add Claim Links page under Wallets section in the left navigation
- Tested locally
> chore: add Claim Links under Wallets left navigation

- docs/documentation/concepts/policy-management/Policy-language.md
This PR updates the policy engine documentation to include the new activity type version `UPDATE_POLICY_V2`
> Update Policy Language docs to include `UPDATE_POLICY_V2`

- authentication/passkeys/integration.mdx
- getting-started/launch-checklist.mdx
thread here: https://turnkeycrypto.slack.com/archives/C04LS7Z9LMS/p1744204382043369
> passkeys & launch checklist minor updates

- changelogs/api-key-stamper/readme.mdx
- changelogs/cosmjs/readme.mdx
- changelogs/crypto/readme.mdx
- changelogs/dart/readme.mdx
- changelogs/eip-1193-provider/readme.mdx
- changelogs/encoding/readme.mdx
- changelogs/ethers/readme.mdx
- changelogs/golang/readme.mdx
- changelogs/http/readme.mdx
- changelogs/iframe-stamper/readme.mdx
- changelogs/react-native-passkey-stamper/readme.mdx
- changelogs/sdk-browser/readme.mdx
- changelogs/sdk-react-native/readme.mdx
- changelogs/sdk-react/readme.mdx
- changelogs/sdk-server/readme.mdx
- changelogs/solana/readme.mdx
- changelogs/telegram-cloud-storage-stamper/readme.mdx
- changelogs/viem/readme.mdx
- changelogs/wallet-stamper/readme.mdx
- changelogs/webauthn-stamper/readme.mdx
- docs.json
Adding Changelogs to Mintlify documentation
There will be a separate PR in `tkhq/sdk` to automatically generate updated changelogs and push them into `tkhq/docs`
> feat: add changelogs to documentation

- assets/files/sms-prices.csv
- authentication/sms.mdx
> SMS pricing and enabling info

- wallets/export-wallets.mdx
Noticed a bit of a confusion around wallet accounts and raw private key export
> Detail over the types of export and resulting key material 

- authentication/email.mdx
- authentication/sms.mdx
Quick update for OTP section of docs
> Docs update for otp

- developer-reference/api-overview/errors.mdx
covering also the MarshalBinary() function behavior
> Add the "failed to parse transaction" error details

- authentication/sms.mdx
> remove old copy on SMS policy

- getting-started/embedded-wallet-quickstart.mdx
- some esthetic updates
- using getSession() with indexedDbClient
- need to match the Ethereum wallet account for this specific signRawPayload params
- added also logout
> update embedded wallets quickstart

- sdks/javascript-server.mdx
This PR removes an incorrect vercel link from the docs
> Remove vercel link

- embedded-wallets/code-examples/wallet-auth.mdx
- walletClient.login is deprecated, updated it to use a rw session instead
- I've also simplified a bit the flow
> Update Wallet Authentication

- concepts/policies/examples.mdx
need to explicitly call this, quite a few people stumbled recently
> add init-otp policy example

- networks/sui.mdx
`@mysten/sui.js` is deprecated, update the example to work with `@mysten/sui`
> update SUI docs example

- authentication/overview.mdx
- developer-reference/api-overview/stamps.mdx
Referenced the example in the wallet auth overview
> Reference the example in the wallet auth overview

- getting-started/embedded-wallet-quickstart.mdx
it as importing SessionType instead of Session
> import Session instead of SessionType

- authentication/email.mdx
- authentication/sms.mdx
- public_api.swagger.json
- Opening this PR in case we need this
> add public_api.swagger.json back to the repo

- README.md
- openapi.json
- public_api.swagger.json
- Add steps to the README.md on how to update the openapi.json with a mono release
> update docs with mono v2025.8.1

- snippets/shared/fiat-on-ramp.mdx
- update onramp KYB process with provider agnostic requirements
> update onramp KYB process

- concepts/overview.mdx
- developer-reference/api-overview/errors.mdx
- faq.mdx
context:
https://turnkeycrypto.slack.com/archives/C04LS7Z9LMS/p1759523063385399
> fix network overview links
